apiVersion: apps/v1beta1
kind: Deployment # it is a deployment
metadata:
  name: endpoints # name of the Deployment
spec:
  # ReplicaSet specification
  replicas: 3 # we are making 3 Pods
  template:
    spec:
      # Pod specification
      containers:
        # the container(s) in this Pod
        - name: partone-container
          image: gcr.io/PROJECT_NAME/partone-container:latest
          # the readiness probe details
          readinessProbe:
            httpGet: # make an HTTP request
              port: 8080 # port to use
              path: /readiness # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 3 # how long to wait before checking
            periodSeconds: 3 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 1 # how many failures to accept before failing
            timeoutSeconds: 1 # how long to wait for a response
          # # the livenessProbe probe details
          # livenessProbe:
          #   httpGet: # make an HTTP request
          #     port: 8080 # port to use
          #     path: /healthcheck # endpoint to hit
          #     scheme: HTTP # or HTTPS
          #   initialDelaySeconds: 3 # how long to wait before checking
          #   periodSeconds: 3 # how long to wait between checks
          #   successThreshold: 1 # how many successes to hit before accepting
          #   failureThreshold: 1 # how many failures to accept before failing
          #   timeoutSeconds: 1 # how long to wait for a response
